# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
# RATING_FIELD: rating
TIME_FIELD: timestamp
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 25
POSITION_FIELD: position_id
load_col:
    inter: [user_id, item_id, timestamp] #  rating,

# data filtering for interactions
# val_interval:
#     rating: "[3,inf)"    
# unused_col: 
#     inter: [rating]

user_inter_num_interval: "[10,inf)"
item_inter_num_interval: "[10,inf)"

# training and evaluation
epochs: 30
stopping_step: 4
train_batch_size: 2048
eval_batch_size: 1024
valid_metric: NDCG@10
eval_args:
    split: {'LS': 'valid_and_test'}
    mode: full
    order: TO

# disable negative sampling
train_neg_sample_args: ~

# model
embedding_size: 64
inner_size: 64
dropout_prob: 0.2
gpu_id: 0
use_gpu: True
worker: 0
reproducibility: True